Repository typst/codex, pull requests merged in 2025-06, with the labels that each got.

#70 Rename angle.spheric.top to angle.spheric.t
  src/modules/sym.txt
Labels: breaking

#46 Codify and Resolve modifiers
  build.rs
  src/lib.rs
  src/shared.rs
Labels: meta

#90 Add and deprecate post 0.13.1 removals
  src/modules/sym.txt
Labels: waiting on reviews

#20 Add math styling module
  Cargo.toml
  src/lib.rs
  src/styling.rs
Labels: meta

#92 Allow multi-character symbols/variants
  build.rs
  src/lib.rs
  src/modules/sym.txt
Labels: meta
