Repository typst/codex, pull requests merged in 2025-07, with the labels that each got.

#62 Rename circle modifier for symbols that are circled to "o"
  src/lib.rs
  src/modules/sym.txt
Labels: breaking, waiting on reviews

#91 Add bullets
  src/modules/sym.txt
Labels: waiting on reviews

#96 Fix docs
  src/lib.rs
  src/shared.rs
Labels: meta

#97 Additional circled mathematical symbols
  src/modules/sym.txt
Labels: waiting on reviews

#110 Add missing arc modifier to `angle.right.dot`, rename `angle.right.sq`
  src/modules/sym.txt
Labels: breaking
